# Generated by Django 3.0.6 on 2020-06-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0003_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=255)),
                ('RegistrtionNo', models.IntegerField()),
                ('Picture', models.FileField(upload_to='profile/')),
                ('AdmissionDate', models.DateField()),
                ('DiscountFee', models.IntegerField()),
                ('MobileNo', models.IntegerField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Addclass')),
            ],
        ),
    ]
