# Generated by Django 3.0.6 on 2020-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=255)),
                ('Picture', models.FileField(blank=True, upload_to='employees/')),
                ('JoiningDate', models.DateField()),
                ('EmployeeType', models.CharField(choices=[('----Employee Type-------', '----Employee Type-------'), ('Teaching', 'Teaching'), ('Non Teaching', 'Non Teaching')], default='----Employee Type-------', max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('MonthlySalary', models.FloatField()),
            ],
        ),
    ]
