# Generated by Django 3.0.6 on 2020-06-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.DateField()),
                ('IncomeDescription', models.CharField(max_length=255)),
                ('IncomeAmount', models.IntegerField()),
            ],
        ),
    ]
