# Generated by Django 3.0.6 on 2020-07-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0007_accountexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.DateField()),
                ('IncomeDescription', models.CharField(default='no description', max_length=255)),
                ('IncomeAmount', models.IntegerField(default=0)),
                ('ExpenseDescription', models.CharField(default='no description', max_length=255)),
                ('ExpenseAmount', models.IntegerField(default=0)),
            ],
        ),
    ]
