# Generated by Django 3.0.6 on 2020-07-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0008_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Attendance', models.CharField(choices=[('present', 'P'), ('absent', 'A'), ('leave', 'L')], max_length=20)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Addclass')),
                ('StudentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Student')),
            ],
        ),
    ]
