# Generated by Django 3.0.6 on 2020-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0010_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('EmpId', models.IntegerField()),
                ('EmployeeName', models.CharField(max_length=255)),
                ('EmployeeType', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
