# Generated by Django 3.0.6 on 2020-08-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0011_employeeattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeeDate', models.DateField()),
                ('RegistrtionId', models.IntegerField()),
                ('StudentName', models.CharField(max_length=255)),
                ('MonthlyFee', models.IntegerField()),
                ('AdmissionFee', models.IntegerField()),
                ('RegistrtionFee', models.IntegerField()),
                ('PreviousBalance', models.IntegerField()),
                ('DiscountFee', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Deposit', models.IntegerField()),
                ('DueBalance', models.IntegerField()),
                ('StudentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Addclass')),
            ],
        ),
    ]
