# Generated by Django 3.0.6 on 2020-08-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0013_feesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
